apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 4001  # The port on which the service will be exposed
      targetPort: 4001  # The port the application is listening on in the container
  type: LoadBalancer # Use LoadBalancer to expose the service to the outside world
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 3  # Number of default pods
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: docker4asinkan/svatba:latest  # Replace with your Docker image
          ports:
            - containerPort: 4001
