apiVersion: v1
kind: Service
metadata:
  name: nextjs-svatba
spec:
  type: NodePort
  selector:
    app: svatba-app
  ports:
    - protocol: TCP
      port: 80          # Exposing the service on port 80 (common for HTTP traffic)
      targetPort: 3000   # The port where the Next.js app listens inside the container
      nodePort: 30000    # External access via <NodeIP>:30000
