name: Build and Deploy Next.js Docker App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: |
          docker build -t ${{ vars.DOCKERHUB_LOGIN }}/svatba:latest .

      - name: Push Docker Image
        run: |
          docker push ${{ vars.DOCKER_LOGIN }}/svatba:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: SSH into server and deploy container
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PASS }}
          script: |
            docker pull ${{ vars.DOCKERHUB_LOGIN }}/svatba:latest
            docker stop svatba || true
            docker rm svatba || true
            docker run -d --net=host --name svatba ${{ vars.DOCKERHUB_LOGIN }}/svatba:latest